"""Criterion 10: a committed golden scenario of about 40 synthetic fills matches its expectation.

Three sources of truth, and each test below joins two of them:

* `golden/expected.json` was generated by the `Fraction` oracle from `golden/scenario.json`
  (`python -m tests.domain.accounting.oracle`), and committed before the engine existed. It
  was **never produced by running the engine under test**.
* The oracle must still reproduce it, so a hand edit to either file, or a change to the
  oracle, is a red test rather than a silent drift between the three.
* The round-number figures were checked by hand, and are asserted below as literals with
  the arithmetic beside them, so the oracle is itself held to something it did not compute.

The scenario is synthetic: invented quantities and prices, no account figures, no addresses.
Its rows are shuffled in the file, so the engine has to sort them; one fill appears twice,
spelled differently; and a transfer shares a trade's whole key.
"""

from __future__ import annotations

import json
from decimal import Decimal
from typing import Any, Final

from portfolio.domain.accounting import AccountingConfig, replay
from tests.domain.accounting import oracle
from tests.domain.accounting.support import engine_to_json, to_engine

SCENARIO: Final = oracle.load_scenario()
CASH: Final = SCENARIO[0]
EVENTS: Final = SCENARIO[1]
#: Parsed JSON, so `Any` by nature: every field is asserted on its value below.
EXPECTED: Final[dict[str, Any]] = json.loads(oracle.EXPECTED_PATH.read_text(encoding="utf-8"))


def engine_result() -> dict[str, object]:
    return engine_to_json(replay([to_engine(event) for event in EVENTS], AccountingConfig(CASH)))


def positions_by_asset() -> dict[str, dict[str, Any]]:
    positions = EXPECTED["positions"]
    assert isinstance(positions, list)
    return {entry["asset"]: entry for entry in positions}


def test_the_scenario_is_the_size_and_shape_the_criterion_asks_for() -> None:
    """About 40 fills, with adjustments and transfers beside them, over several assets."""
    trades = [event for event in EVENTS if isinstance(event, oracle.Trade)]
    adjustments = [event for event in EVENTS if isinstance(event, oracle.Adjustment)]
    transfers = [event for event in EVENTS if isinstance(event, oracle.Transfer)]

    assert 35 <= len(trades) <= 45
    assert len(adjustments) >= 2
    assert len(transfers) >= 1
    assert {event.asset for event in adjustments} >= {"ETH", "DOGE", "KAS", "USDT"}
    assert len({asset for event in trades for asset in (event.base_asset, event.quote_asset)}) >= 6
    # The rows are not in replay order: the engine has to sort them.
    assert oracle.ordered(EVENTS) != EVENTS


def test_the_oracle_still_reproduces_the_committed_expectation() -> None:
    """A hand edit to the golden files, or a change to the oracle, is visible here."""
    assert json.loads(oracle.expected_document()) == EXPECTED


def test_the_engine_matches_the_golden_expectation() -> None:
    """Criterion 10: every position, warning, lot, unallocated cost and the event count."""
    assert engine_result() == EXPECTED


def test_the_engine_matches_whatever_order_the_rows_arrive_in() -> None:
    """The file order, reversed: the same answer, down to the fingerprint."""
    config = AccountingConfig(CASH)
    forward = replay([to_engine(event) for event in EVENTS], config)
    backward = replay([to_engine(event) for event in reversed(EVENTS)], config)

    assert backward == forward
    assert backward.input_fingerprint == forward.input_fingerprint


# --------------------------------------------------------------------------------------
# The hand check: round numbers, worked out without the oracle
# --------------------------------------------------------------------------------------


def test_hand_check_event_count() -> None:
    """45 rows, one of which is g03 read a second time with `0.250`/`15000.000`/`15.0`."""
    assert EXPECTED["event_count"] == 44


def test_hand_check_ada_residue_lands_in_realized() -> None:
    """ADA: 3000 bought for 100, sold 1000 / 700 / 1300 for 39.96 / 30 / 59.94 net.

    Proceeds 129.9 against a cost of 100: realized is exactly 29.9 however the three basis
    shares rounded, because the last sale takes whatever basis is left.
    """
    ada = positions_by_asset()["ADA"]

    assert Decimal(ada["quantity"]) == 0
    assert Decimal(ada["cost_basis"]) == 0
    assert ada["average_cost"] is None
    assert Decimal(ada["realized_pnl"]) == Decimal("29.9")
    assert ada["flags"] == []


def test_hand_check_bgb_is_carried_at_one_and_a_half() -> None:
    """BGB: 100 bought for 150 (1.5 each), after a 0.5 BGB fee that found no BGB at all.

    Then 0.9 paid as a fee (1.35 of basis), 50 sold for 80 (75 of basis, realized 5), 0.25
    paid on a conversion (0.375), 0.3 paid on a swap (0.45), and 0.2 rebated at unknown cost.
    Known: 100 - 0.9 - 50 - 0.25 - 0.3 = 48.55 at 1.5 = 72.825. Total 48.75.
    """
    bgb = positions_by_asset()["BGB"]

    assert Decimal(bgb["quantity"]) == Decimal("48.75")
    assert Decimal(bgb["unknown_basis_quantity"]) == Decimal("0.2")
    assert Decimal(bgb["cost_basis"]) == Decimal("72.825")
    assert Decimal(bgb["average_cost"]) == Decimal("1.5")
    assert Decimal(bgb["realized_pnl"]) == Decimal(5)
    assert bgb["flags"] == ["HISTORY_INCOMPLETE", "UNKNOWN_BASIS"]


def test_hand_check_doge_is_all_unknown() -> None:
    """DOGE: 1000 at unknown cost, 400 swapped away. 600 left, none of it with a cost."""
    doge = positions_by_asset()["DOGE"]

    assert Decimal(doge["quantity"]) == 600
    assert Decimal(doge["unknown_basis_quantity"]) == 600
    assert Decimal(doge["cost_basis"]) == 0
    assert doge["average_cost"] is None
    assert doge["flags"] == ["UNKNOWN_BASIS"]


def test_hand_check_eth_oversell() -> None:
    """ETH before the oversell: 0.5 for 1601.6, 1 for 2999.7, 1 for 3099.5, 2.3 adjusted at
    5750.283950614728395059, plus 0.05 of unknown cost from the DOGE swap.

    Selling 6 for 21000 less 21: 4.8 known of 6, so 20979 x 4.8 / 6 = 16783.2 matched and
    4195.8 unmatched; realized 16783.2 - 13451.083950614728395059. Later ETH events are
    buys and a swap, which realize nothing.
    """
    eth = positions_by_asset()["ETH"]

    assert Decimal(eth["realized_pnl"]) == Decimal("16783.2") - Decimal("13451.083950614728395059")
    assert Decimal(eth["unmatched_proceeds"]) == Decimal("4195.8")
    assert "HISTORY_INCOMPLETE" in eth["flags"]


def test_hand_check_unallocated_costs() -> None:
    """0.375 (a conversion fee of 0.25 BGB at 1.5) + 0.2 (a swap whose received side had no
    known part) + 1 (a conversion fee in USDT) + 0.2 (a conversion fee in the USDT received).
    """
    assert Decimal(EXPECTED["unallocated_costs"]) == Decimal("1.775")


def test_hand_check_no_position_for_cash_or_for_a_zero_fee_asset() -> None:
    """USDT and USDC are cash; SOL is only ever named beside a zero fee (R8)."""
    assert set(positions_by_asset()) == {"ADA", "BGB", "BTC", "DOGE", "ETH", "KAS"}


def test_hand_check_warnings() -> None:
    """Three shortfalls and one unattributed fee, in event order.

    * BTC, 0.25: "1000" sorts before "999" at the same millisecond, so 1 BTC is sold while
      0.75 is held.
    * BGB, 0.5, and the fee charged to BTC: no BGB had been bought yet.
    * ETH, 1.15: 6 sold with 4.85 held.
    """
    summary = [
        (
            warning["type"],
            warning.get("asset", warning.get("fee_asset")),
            Decimal(warning.get("shortfall", warning.get("quantity"))),
            warning["key"]["external_id"],
        )
        for warning in EXPECTED["warnings"]
    ]

    assert summary == [
        ("negative_inventory", "BTC", Decimal("0.25"), "1000"),
        ("negative_inventory", "BGB", Decimal("0.5"), "g05"),
        ("unattributed_fee", "BGB", Decimal("0.5"), "g05"),
        ("negative_inventory", "ETH", Decimal("1.15"), "g16"),
    ]
    assert EXPECTED["warnings"][2]["charged_to"] == "BTC"


def test_hand_check_btc_after_the_same_millisecond_pair() -> None:
    """A prefix, by hand: 0.5 + 0.4995 + 0.0005 = 1 BTC for 45050, 0.25 sold for 14985 net.

    Realized 14985 - 11262.5 = 3722.5. Then the pair: 1 sold holding 0.75 (basis 33787.5),
    72000 x 0.75 = 54000 matched, 18000 unmatched, realized 54000 - 33787.5 = 20212.5. Then
    0.25 bought for 17000.
    """
    cutoff = oracle.parse_time("2026-02-05T12:00:00.123000Z")
    prefix = [event for event in EVENTS if event.key.occurred_at <= cutoff]
    result = engine_to_json(replay([to_engine(event) for event in prefix], AccountingConfig(CASH)))
    positions: list[dict[str, Any]] = result["positions"]  # type: ignore[assignment]
    (btc,) = positions

    assert Decimal(btc["realized_pnl"]) == Decimal("23935")
    assert Decimal(btc["unmatched_proceeds"]) == Decimal("18000")
    assert Decimal(btc["quantity"]) == Decimal("0.25")
    assert Decimal(btc["cost_basis"]) == Decimal("17000")
